<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;

class CreateUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::insert([
            [
                'firstname' => 'Morice',
                'lastname' => 'Ishimwe',
                'gender' => 'male',
                'phone' => '0780012345',
                'email' => 'email1@gmail.com',
                'dob' => '20/12/2000',
                'username' => 'user1111',
                'password' => bcrypt('password'),
                'image' => 'user.png',
                'province' => 'kigali',
                'district' => 'Nyarugenge',
                'created_at' => '2024-08-02 09:17:10',
                'updated_at' => '2024-08-02 09:17:10',
            ],[
                'firstname' => 'Elyse',
                'lastname' => 'Niyonkuru',
                'gender' => 'male',
                'phone' => '0780012342',
                'email' => 'email2@gmail.com',
                'dob' => '20/12/2000',
                'username' => 'user2222',
                'password' => bcrypt('password'),
                'image' => 'user.png',
                'province' => 'kigali',
                'district' => 'Nyarugenge',
                'created_at' => '2024-08-02 09:17:10',
                'updated_at' => '2024-08-02 09:17:10',
            ],[
                'firstname' => 'Yvette',
                'lastname' => 'Abayo',
                'gender' => 'female',
                'phone' => '0780012343',
                'email' => 'email3@gmail.com',
                'dob' => '20/12/2000',
                'username' => 'user3333',
                'password' => bcrypt('password'),
                'image' => 'user.png',
                'province' => 'kigali',
                'district' => 'Nyarugenge',
                'created_at' => '2024-08-05 09:17:10',
                'updated_at' => '2024-08-05 09:17:10',
            ],[
                'firstname' => 'Nadine',
                'lastname' => 'Niyonsaba',
                'gender' => 'female',
                'phone' => '0780012344',
                'email' => 'email4@gmail.com',
                'dob' => '20/12/2000',
                'username' => 'user4444',
                'password' => bcrypt('password'),
                'image' => 'user.png',
                'province' => 'Eastern',
                'district' => 'Kayonza',
                'created_at' => '2024-08-07 09:17:10',
                'updated_at' => '2024-08-07 09:17:10',
            ],[
                'firstname' => 'Diane',
                'lastname' => 'Ishimwe',
                'gender' => 'female',
                'phone' => '0780012346',
                'email' => 'email5@gmail.com',
                'dob' => '20/12/2000',
                'username' => 'user5555',
                'password' => bcrypt('password'),
                'image' => 'user.png',
                'province' => 'Western',
                'district' => 'Rubavu',
                'created_at' => '2024-08-07 09:17:10',
                'updated_at' => '2024-08-07 09:17:10',
            ],[
                'firstname' => 'Eric',
                'lastname' => 'Ahirwe',
                'gender' => 'male',
                'phone' => '0780012347',
                'email' => 'email6@gmail.com',
                'dob' => '20/12/2000',
                'username' => 'user6666',
                'password' => bcrypt('password'),
                'image' => 'user.png',
                'province' => 'Northen',
                'district' => 'Kayonza',
                'created_at' => '2024-08-12 09:17:10',
                'updated_at' => '2024-08-12 09:17:10',
            ],[
                'firstname' => 'Eugene',
                'lastname' => 'Mugisha',
                'gender' => 'male',
                'phone' => '0780012353',
                'email' => 'email7@gmail.com',
                'dob' => '20/12/2000',
                'username' => 'user7777',
                'password' => bcrypt('password'),
                'image' => 'user.png',
                'province' => 'Northen',
                'district' => 'Rulindo',
                'created_at' => '2024-08-13 09:17:10',
                'updated_at' => '2024-08-13 09:17:10',
            ],[
                'firstname' => 'Mireille',
                'lastname' => 'Mukeshimana',
                'gender' => 'female',
                'phone' => '0780012348',
                'email' => 'email8@gmail.com',
                'dob' => '20/12/2000',
                'username' => 'user8888',
                'password' => bcrypt('password'),
                'image' => 'user.png',
                'province' => 'Eastern',
                'district' => 'Bugesera',
                'created_at' => '2024-08-15 09:17:10',
                'updated_at' => '2024-08-15 09:17:10',
            ],[
                'firstname' => 'Dina',
                'lastname' => 'Mpogazi',
                'gender' => 'female',
                'phone' => '0780012349',
                'email' => 'email9@gmail.com',
                'dob' => '20/12/2000',
                'username' => 'user9999',
                'password' => bcrypt('password'),
                'image' => 'user.png',
                'province' => 'Western',
                'district' => 'Nyamasheke',
                'created_at' => '2024-08-15 09:17:10',
                'updated_at' => '2024-08-15 09:17:10',
            ],[
                'firstname' => 'Busra',
                'lastname' => 'Mukeshimana',
                'gender' => 'female',
                'phone' => '0780012350',
                'email' => 'email10@gmail.com',
                'dob' => '20/12/2000',
                'username' => 'user11111',
                'password' => bcrypt('password'),
                'image' => 'user.png',
                'province' => 'kigali',
                'district' => 'Nyarugenge',
                'created_at' => '2024-08-18 09:17:10',
                'updated_at' => '2024-08-18 09:17:10',
            ],[
                'firstname' => 'Claudina',
                'lastname' => 'Ishimwe',
                'gender' => 'female',
                'phone' => '0780012351',
                'email' => 'email11@gmail.com',
                'dob' => '20/12/2000',
                'username' => 'user22222',
                'password' => bcrypt('password'),
                'image' => 'user.png',
                'province' => 'Northen',
                'district' => 'Musanze',
                'created_at' => '2024-08-19 09:17:10',
                'updated_at' => '2024-08-19 09:17:10',
            ]
        ]);
    }
}
